config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  post '/new_user_reaction', to: 'reactions#new_user_reaction', as: 'new_user_reaction'

  # resources :comments, only: [:create]
  resources :comments, only: [:create] do
    post :create_anonymous_comment, on: :collection
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy
    has_many :users, through: :reactions

    Kinds = %w[like dislike].freeze
    KindsSpanish = {"like" => "Me gusta", "dislike" => "No me gusta"}.freeze
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reactions
  has_many :comments
  has_many :posts, through: :reactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:comment][:post_id])
        @comment = Comment.new(comment_params)
        @comment.user = current_user

        respond_to do |format|
            if @comment.save
                format.html { redirect_to post_path(@post.id), notice: 'El comentario fue creado.' }
            else
                format.html { redirect_to post_path(@post.id), notice: 'El comentario no fue creado.' }
            end
        end
    end

    def create_anonymous_comment
        @post = Post.find(params[:comment][:post_id])
        @comment = Comment.new(comment_params)
        @comment.user = nil
        # set other necessary attributes for anonymous comment
        respond_to do |format|
            if @comment.save
                format.html { redirect_to post_path(@post.id), notice: 'El comentario fue creado.' }
            else
                format.html { redirect_to post_path(@post.id), notice: 'El comentario no fue creado.' }
            end
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :post, :pic)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    
    def new_user_reaction
        @user = current_user
        @post = Post.find(params[:post_id]) if params[:post_id]
        @kind = params[:kind]
        
        respond_to do |format|
            (@type == "post") ? @reaction = Reaction.new(user_id: @user.id, post_id: @post.id, reaction_type: @type, kind: @kind) : @reaction = Reaction.new(user_id: @user.id, comment_id: @comment.id, reaction_type: @type, kind: @kind)
            if @reaction.save!
                format.html { redirect_to post_path(@post), notice: 'La reaccion fue exitosamente creada' }
            else
                format.html { redirect_to post_path(@post), notice: 'Algo salio mal' }
            end
            end
        end            
    end

    def like
        @post = Post.find(params[:post_id]) if params[:post_id]
        @post.increment!(:likes_count)
        redirect_to @post
    end    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/_article_comments.html.erb
<div>
    <% @comments.reverse_each do |comment| %>
        <div>
            <% if current_user %>
                <strong><%= comment.user.name %></strong>
            <% else %>
                <strong>Anónimo</strong>
            <% end %>
            <p><%= comment.content %></p>
        </div>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id = 'error_explanation'>
      <h2>Este comentario no se pudo crear por las siguientes razones</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :post_id, value: @post.id %>
  
  <div class = 'field'>
    <%= f.label :content, as: "Contenido" %>
    <%= f.text_field :content %>
  </div>  

  <div class = 'actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <div class="container" style="width: 1000px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :post, style: "display: block" %>
    <%= form.text_field :post %>
  </div>

  <div>
    <%= form.label :pic, style: "display: block" %>
    <%= form.text_field :pic %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <div class="text-center">
    <%= image_tag( post.pic, alt: "Gatito", height: "auto", width: "800") %>
  </div>
  <br>
  <p>
    <strong>Post:</strong>
    <%= post.post %>
  </p>
  
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>
<%= link_to "Nuevo post", new_post_path %>
<br>
<div id="posts" class="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Ver este post", post %>
    </p>
  <% end %>
</div>
<br>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Editar este post", edit_post_path(@post) %> |
  <%= link_to "Volver a posts", posts_path %>
  <br>
  <%= button_to "Eliminar este post", @post, method: :delete %>
  <br>
  <% Post::Kinds.each do |kind| %>
    <div class="d-inline-block">
      <%= button_to "#{Post::KindsSpanish[kind]}", new_user_reaction_path(post_id: @post.id, reaction_type: "post", kind: kind), method: :post %>
    </div>
  <% end %>

</div>
<br>
<%= render 'comments/form' %>
<br>
<%= render 'comments/article_comments' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <%= link_to 'Crazy4Cats', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Posts', posts_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%# <%= link_to 'Tus reacciones', my_reactions_path, class: 'nav-link' %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <% if user_signed_in? %>
                            <% if current_user.name %>
                                Hola <%= current_user.name %>
                            <% else %>
                                Hola <%= current_user.email %>
                            <% end %>
                        <% else %>
                            Dale registrate o conectate
                        <% end %>
                    </a>
                    <ul class="dropdown-menu">
                        <% if user_signed_in? %>
                            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                        <% else %>
                            <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>